name: F2FS Compression

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [ginkgo-current, laurel_sprout-current]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing kernel sources
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
            rm -rf android_kernel_xiaomi_sm6125
          fi
          if [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.2
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.2
          fi
          cp build.sh android_kernel_xiaomi_sm6125/
          chmod +x ./android_kernel_xiaomi_sm6125/build.sh

      - name: Apply F2FS Compression Patch
        run: | 
          cd android_kernel_xiaomi_sm6125/
          echo "Apply revert patch for current"
          wget -qO- "https://github.com/LineageOS/android_kernel_xiaomi_sm6125/commit/212f6697ff90336cc993d163411775ec969deeb6.patch" | patch -R -p1
          wget -qO- "https://github.com/LineageOS/android_kernel_xiaomi_sm6125/commit/694585a55caa3e1873c889ab3aa1c47d93144fad.patch" | patch -R -p1
          echo "Apply the compression support"
          wget -qO- "https://github.com/tbyool/android_kernel_xiaomi_sm6150/commit/02baeab5aaf5319e5d68f2319516efed262533ea.patch" | patch -p1
          echo "Enable the COmpression support"
          echo "CONFIG_F2FS_FS_COMPRESSION=y" >> arch/arm64/configs/vendor/trinket-perf_defconfig
          echo "CONFIG_F2FS_FS_LZ4=y" >> arch/arm64/configs/vendor/trinket-perf_defconfig
          cd ..

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6125/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_NEXT
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config laurel_sprout.config --ksu=KSU_NEXT
          fi
          cd ..

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=willow/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/ginkgo willow (sm6125)/g' AnyKernel3/banner
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/laurel_sprout (sm6125)/g' AnyKernel3/banner
          fi

      - name: Pack & upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: perf-neon-${{ matrix.build-type }}-f2fs_compression-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}
          path: |
            AnyKernel3/*
