name: Testing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [ginkgo-legacy, ginkgo-current, laurel_sprout-legacy, laurel_sprout-current]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing kernel sources
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
            rm -rf android_kernel_xiaomi_sm6125
          fi
          if [[ "${{ matrix.build-type }}" == "ginkgo-legacy" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.2
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-legacy" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.2
          fi
          cp build.sh android_kernel_xiaomi_sm6125/
          chmod +x ./android_kernel_xiaomi_sm6125/build.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6125/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "ginkgo-legacy" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_BLXX
          elif [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_BLXX
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-legacy" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config laurel_sprout.config --ksu=KSU_BLXX
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config laurel_sprout.config --ksu=KSU_BLXX
          fi
          cd ..

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "ginkgo-legacy" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=willow/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/ginkgo willow (sm6125)/g' AnyKernel3/banner
          elif [[ "${{ matrix.build-type }}" == "ginkgo-current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=willow/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/ginkgo willow (sm6125)/g' AnyKernel3/banner
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-legacy" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/laurel_sprout (sm6125)/g' AnyKernel3/banner
          elif [[ "${{ matrix.build-type }}" == "laurel_sprout-current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=laurel_sprout/' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/laurel_sprout (sm6125)/g' AnyKernel3/banner
          fi

      - name: Pack & upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: perf-neon-${{ matrix.build-type }}-testing-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}
          path: |
            AnyKernel3/*
